services:
  postgres:
    image: postgres:18
    restart: "always"
    ports:
      - 5432:5432 # dev only
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/pg18
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: adminer
    networks:
      - backend
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  # api:
  #   build:
  #     context: .
  #     dockerfile: apps/api/Dockerfile
  #   restart: always
  #   env_file:
  #     - ./apps/api/.env.development
  #   container_name: api
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./apps/api/src
  #         target: /app/apps/api/src
  #         ignore:
  #           - ./node_modules/
  #       - action: rebuild
  #         path: ./apps/api/package.json
  #       - action: sync
  #         path: ./packages/shared/src
  #         target: /app/packages/shared/src
  #         ignore:
  #           - ./node_modules/
  #       - action: rebuild
  #         path: ./packages/shared/package.json
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - backend
  #   ports:
  #     - 5000:5000
  
  # web:
  #   build:
  #     context: .
  #     dockerfile: apps/web/Dockerfile
  #   restart: always
  #   container_name: web
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./apps/web/src
  #         target: /app/apps/web/src
  #         ignore:
  #           - ./node_modules/
  #       - action: rebuild
  #         path: ./apps/web/package.json
  #       - action: sync
  #         path: ./packages/shared/src
  #         target: /app/packages/shared/src
  #         ignore:
  #           - ./node_modules/
  #       - action: rebuild
  #         path: ./packages/shared/package.json
  #   depends_on:
  #     - api
  #   networks:
  #     - backend
  #   ports:
  #     - 3000:3000

  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - 80:80
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/default.conf:ro
  #   depends_on:
  #     - api
  #     - web
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
  app_network:
    # external: true

volumes:
  pg_data: