services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=master123
      - POSTGRES_DB=postgres
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - backend

  api:
    build:
      dockerfile: ./apps/api/Dockerfile
      context: .
    ports:
      - 5000:5000
    env_file:
      - ./apps/api/.env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local