# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  up:
    cmds:
      - docker compose up --build --watch 
    silent: true
  down:
    cmds:
      - docker compose down -v
  up-prod:
    cmds:
      - docker compose -f docker-compose.prod.yml up --build
  prod-down:
    cmds:
      - docker compose -f docker-compose.prod.yml down -v